import { DM_Sans } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Suspense } from "react";
import Loading from "./loading";

const DMSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: {
    template: " %s / PhotoSnap",
    default: "Welcome / PhotoSnap",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${DMSans.className}  antialiased  `}>
        <div className="max-w-screen overflow-hidden ">
          <Suspense fallback={<Loading />}>
            <Header />
            {children}
            <Footer />
          </Suspense>
        </div>
      </body>
    </html>
  );
}
